//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness_Object_Layer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answertbl
    {
        public int ID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> optionID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual option_tb option_tb { get; set; }
    }
}
