//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness_Object_Layer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marktbl
    {
        public int mark_id { get; set; }
        public int mark { get; set; }
        public int test_id { get; set; }
    
        public virtual test_detailtbl test_detailtbl { get; set; }
    }
}
