//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness_Object_Layer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_examinationEntities : DbContext
    {
        public Online_examinationEntities()
            : base("name=Online_examinationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answertbl> Answertbls { get; set; }
        public virtual DbSet<option_tb> option_tb { get; set; }
        public virtual DbSet<optiontbl> optiontbls { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<test_detailtbl> test_detailtbl { get; set; }
        public virtual DbSet<Marktbl> Marktbls { get; set; }
    }
}
