//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussiness_Object_Layer.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.test_detailtbl = new HashSet<test_detailtbl>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "First Name is Required")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = " Last Name is Required")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Email is Required")]
        public string email { get; set; }
        [Required(ErrorMessage = "password is Required")]
        public string password { get; set; }
        public bool IsActive { get; set; }
        public int RoleId { get; set; }
        [Required(ErrorMessage = "OTP is Required")]
        public Nullable<int> otp { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_detailtbl> test_detailtbl { get; set; }
    }
}
